- name: Install python dependencies
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    force_apt_get: yes
  with_items:
    - python
    - python-setuptools 
    - python-dev
    - build-essential 
    - python-pip
    - python-mysqldb
